/**
 * The director's type: for each directing style (src/lib/styles), what its
 * titles, credits and captions actually use — surveyed from the films, the
 * trailers and the channels — translated into a bundled face, a case, a
 * colour, an entrance and the roles the style puts on the frame. Where the
 * real typeface cannot be bundled (Futura, Gotham, Helvetica, Trajan…) an
 * open-licence stand-in is named in `standsFor`; where the survey found
 * nothing, `note` says the choice is an assumption.
 *
 * add_text_overlay {role} resolves through this; check_text holds the
 * supporting overlays to its faces, case and roles; film titles can have an
 * independent display treatment. guide/styles/<id>.md carries the surveyed
 * profiles in its "Type" section
 * (generated by scripts/gen-style-type.ts).
 */
import { styleById } from "../styles";
import type { FontId } from "./fonts";
import { TYPE_PRESETS, applyPreset, presetById, type OverlayFields, type TextAnimationId, type Transform, type TypePreset } from "./presets";

export type TypeRole = "title" | "card" | "intertitle" | "lower-third" | "caption" | "callout" | "citation" | "date" | "quote" | "label" | "credit";
export const TYPE_ROLES: TypeRole[] = ["title", "card", "intertitle", "lower-third", "caption", "callout", "citation", "date", "quote", "label", "credit"];

/** A role's overrides on top of a base preset. */
export interface RoleSpec {
  /** the generic preset this role starts from (src/lib/typography/presets) */
  preset: string;
  font?: FontId;
  transform?: Transform;
  sizePct?: number;
  sizePctVertical?: number;
  position?: string;
  color?: string;
  boxEnabled?: boolean;
  boxColor?: string;
  boxOpacity?: number;
  outlineW?: number;
  shadow?: number;
  animation?: TextAnimationId;
  holdS?: number;
  /** what this role is, in the style's own terms */
  use: string;
}

export interface TypeSystem {
  style: string;
  name: string;
  /** Optional type treatments, not creator-wide bans. */
  preferenceOnly?: boolean;
  /** the real typographic signature, in a sentence */
  signature: string;
  /** which bundled faces stand in for which real typefaces */
  standsFor: string;
  faces: FontId[];
  case: "sentence" | "upper" | "lower" | "tracked-upper";
  color: string;
  /** the field a card sits on (black unless the style paints one) */
  field: string;
  motion: TextAnimationId;
  defaultRole: TypeRole;
  roles: Partial<Record<TypeRole, RoleSpec>>;
  /** roles the style does not use (check_text warns) */
  never?: TypeRole[];
  /** the style puts nothing on the frame beyond a title (check_text warns on any overlay) */
  noText?: boolean;
  /** what the survey found (or did not) and how it was translated */
  note: string;
}

const GENERIC_ROLE_PRESET: Record<TypeRole, string> = { title: "title", card: "card-editorial", intertitle: "intertitle", "lower-third": "lower-third", caption: "caption-pop", callout: "callout", citation: "citation", date: "date-card", quote: "quote", label: "map-label", credit: "citation" };

const T = (t: Omit<TypeSystem, "name">, name: string): TypeSystem => {
  const reference = styleById(t.style);
  if (!reference?.craft) return { name, ...t };
  return {
    ...t, name: reference.name, preferenceOnly: true, never: [], noText: false,
    signature: reference.craft.typography,
    standsFor: "Bundled design starting points; exact fonts require a named work/version.",
    note: "Optional project treatments, not a verified career-wide typography system. " +
      "Keep title and supporting text coherent; source labels and accessibility captions are available. " +
      reference.craft.evidence.basis,
  };
};

export const STYLE_TYPE: TypeSystem[] = [
  // ---------------------------------------------------------------- documentary
  T({ style: "adam-curtis", signature: "Two registers: plain white sentence-case supporting cards, and large bold film-title lettering with a deliberately vivid palette. Bitter Lake uses turquoise capitals; Can't Get You Out of My Head artwork uses cyan with a yellow offset on red.", standsFor: "Liberation Sans Regular for neutral supporting text; Liberation Sans Bold as a bundled approximation of the bold title grotesk. The original title font and exact colors have not been verified.", faces: ["LiberationSans-Regular", "LiberationSans-Bold"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "card",
    roles: { title: { preset: "title", font: "LiberationSans-Bold", transform: "upper", sizePct: 16, sizePctVertical: 11, position: "CENTER", color: "#00DED4", boxEnabled: false, outlineW: 0, shadow: 0, animation: "NONE", holdS: 4, use: "the film name in large, bold colored capitals; start from Bitter Lake turquoise, choose deliberate line breaks, and adapt the palette per film" }, card: { preset: "card-archive", font: "LiberationSans-Regular", transform: "none", sizePct: 5.2, sizePctVertical: 4.2, position: "CENTER", boxEnabled: false, animation: "NONE", holdS: 4, use: "a place and a year, or one sentence of the argument, on black" }, caption: { preset: "card-archive", font: "LiberationSans-Regular", transform: "none", sizePct: 4.6, sizePctVertical: 3.8, position: "CENTER", boxEnabled: false, outlineW: 0, animation: "NONE", holdS: 4, use: "the same sentence, straight over the archive, no box, no outline" }, date: { preset: "date-card", font: "LiberationSans-Regular", transform: "none", sizePct: 3.8, position: "TOP_LEFT", boxEnabled: false, outlineW: 0, animation: "NONE", use: "a place · a year, top-left, the archive's own timecode left in" } },
    never: ["lower-third", "callout", "citation", "intertitle"], note: "Visual title references reviewed 2026-09-09: Bitter Lake title frame (turquoise heavy capitals over footage) and Can't Get You Out of My Head artwork (cyan capitals, yellow offset, red field). See guide/styles/adam-curtis.md for sources and limits. The title role is a Bitter Lake-informed starting point, not a universal Curtis wordmark. #00DED4 and 16%/11% sizes are design choices, not sampled production specifications. NONE remains a harness default; motion was not established from these still references." }, "Adam Curtis"),
  T({ style: "michael-moore", signature: "Broadcast-news grammar: bold Helvetica lower-thirds in a bar, plain white cards on black for the dates and the gags, headlines and documents filling the frame.", standsFor: "Liberation Sans for Helvetica / Arial.", faces: ["LiberationSans-Bold", "LiberationSans-Regular"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "lower-third",
    roles: { "lower-third": { preset: "lower-third", font: "LiberationSans-Bold", sizePct: 3.8, animation: "NONE", use: "name · title, as a newscast would" }, card: { preset: "card-archive", font: "LiberationSans-Bold", transform: "none", sizePct: 5, position: "CENTER", use: "'Two days later' — the gag card, white on black" }, callout: { preset: "callout", font: "LiberationSans-Regular", use: "the highlighted line of a document" } },
    never: ["intertitle", "quote"], note: "Assumption from the films: the lower-thirds and cards imitate 1990s–2000s American news graphics; nothing is designed." }, "Michael Moore"),
  T({ style: "errol-morris", signature: "Plain cards on black in Baskerville — the typeface Morris argued makes a sentence believed — for names, dates and quotations; a heavy title in the same face.", standsFor: "Libre Baskerville for Baskerville.", faces: ["LibreBaskerville-Regular", "LibreBaskerville-Bold"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "LibreBaskerville-Regular", sizePct: 4.6, position: "CENTER", use: "a fact the subject does not say, one sentence on black" }, quote: { preset: "quote", font: "LibreBaskerville-Regular", sizePct: 4, outlineW: 0, use: "a document's phrase, over the document" }, date: { preset: "date-card", font: "LibreBaskerville-Regular", sizePct: 3.6, position: "CENTER", outlineW: 0, use: "a date on black between chapters" }, label: { preset: "date-card", font: "LibreBaskerville-Regular", sizePct: 3.2, position: "BOTTOM_LEFT", outlineW: 0, shadow: 4, holdS: 3.5, use: "the subject's name and role, the first time, small, no bar" }, title: { preset: "title", font: "LibreBaskerville-Bold", transform: "upper", sizePct: 7, shadow: 0, use: "the film's title" } },
    never: ["lower-third", "caption", "callout"], note: "Surveyed: Morris's essay on Baskerville and truth (the New York Times); the films' name cards are plain white serif on black. The Fog of War's title face was not documented; Baskerville is used throughout." }, "Errol Morris"),
  T({ style: "ken-burns", signature: "A book serif in the period's manner: names and dates lower-left under a reading, chapter titles in spaced capitals, ivory on black, slow fades.", standsFor: "EB Garamond for the Garamond-class serifs of the PBS films.", faces: ["EBGaramond-Regular", "EBGaramond-Bold"], case: "sentence", color: "#F2E9D8", field: "#000000", motion: "FADE", defaultRole: "date",
    roles: { date: { preset: "date-card", font: "EBGaramond-Regular", sizePct: 3.6, position: "BOTTOM_LEFT", outlineW: 0, shadow: 3, holdS: 3.5, use: "the writer's name and the date under a reading" }, quote: { preset: "quote", font: "EBGaramond-Regular", sizePct: 4.2, outlineW: 0, use: "a line of a letter over the photograph" }, card: { preset: "card-editorial", font: "EBGaramond-Regular", transform: "tracked-upper", sizePct: 4.6, holdS: 4, use: "a chapter title in spaced capitals on black" }, label: { preset: "date-card", font: "EBGaramond-Regular", sizePct: 3.2, position: "BOTTOM_LEFT", outlineW: 0, shadow: 3, use: "a talking head's name, once" }, title: { preset: "title", font: "EBGaramond-Bold", transform: "tracked-upper", sizePct: 7, shadow: 0, use: "the film's title" } },
    never: ["caption", "callout", "lower-third", "intertitle"], note: "Assumption: the exact faces vary by film and were not documented in the survey; the manner (serif, ivory, lower-left names, spaced capitals for titles) is consistent across the PBS films." }, "Ken Burns"),
  T({ style: "werner-herzog", signature: "A plain serif title on black and nothing else on the frame; the voice does what a caption would.", standsFor: "Liberation Serif for the plain serif of the titles.", faces: ["LiberationSerif-Regular"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "title", noText: true,
    roles: { title: { preset: "title", font: "LiberationSerif-Regular", transform: "none", sizePct: 6, shadow: 0, use: "the title of a standalone film, on black" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "card", "intertitle", "quote", "date"], note: "Surveyed loosely: Grizzly Man and Encounters at the End of the World open on plain titles; nothing is superimposed inside the films." }, "Werner Herzog"),
  T({ style: "frederick-wiseman", signature: "The film's name in plain white sans on black; nothing else, ever.", standsFor: "Liberation Sans for the plain grotesk.", faces: ["LiberationSans-Regular"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "title", noText: true,
    roles: { title: { preset: "title", font: "LiberationSans-Regular", transform: "none", sizePct: 5, shadow: 0, animation: "NONE", use: "the title of a standalone film" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "card", "intertitle", "quote", "date"], note: "Wiseman's titles are a plain name on black; no captions, no names, no dates inside the film." }, "Frederick Wiseman"),
  T({ style: "humphrey-jennings", signature: "Crown Film Unit titles: plain capitals, white on black, an opening card and nothing inside the film.", standsFor: "Noto Sans with spaced capitals for the Gill-Sans-class lettering of the 1940s units.", faces: ["NotoSans-Regular"], case: "tracked-upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "title", noText: true,
    roles: { title: { preset: "title", font: "NotoSans-Regular", transform: "tracked-upper", sizePct: 5.5, shadow: 0, animation: "NONE", use: "the opening title card" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "card", "intertitle", "quote", "date"], note: "Assumption: the survey did not document the title lettering; the wartime units set titles in plain capitals." }, "Humphrey Jennings"),
  T({ style: "lemmino", signature: "Sleek squared display capitals for titles and chapter cards, a quiet serif for documents, everything on black with slow fades.", standsFor: "Bebas Neue for the Bebas-like display face viewers identify; Noto Serif for the document serif.", faces: ["BebasNeue-Regular", "NotoSerif-Regular", "NotoSans-Regular"], case: "upper", color: "#E8E8E8", field: "#0B0B0B", motion: "FADE", defaultRole: "card",
    roles: { title: { preset: "title", font: "BebasNeue-Regular", transform: "tracked-upper", sizePct: 8, shadow: 0, use: "the title" }, card: { preset: "card-editorial", font: "BebasNeue-Regular", transform: "tracked-upper", sizePct: 5, holdS: 3.5, use: "a chapter or a date card on black" }, quote: { preset: "quote", font: "NotoSerif-Regular", sizePct: 3.8, outlineW: 0, use: "the highlighted phrase of a document" }, label: { preset: "map-label", font: "NotoSans-Regular", sizePct: 2.8, use: "a map label" }, citation: { preset: "citation", font: "NotoSans-Regular", use: "a source" } },
    never: ["lower-third", "caption", "callout"], note: "Surveyed: viewers identify the title face as Bebas-like with a squarer finish; the serif and the labels are assumptions." }, "LEMMiNO"),
  // ---------------------------------------------------------------- advertising
  T({ style: "ridley-scott", signature: "The closing copy in a Garamond (the 1984 spot's Apple Garamond), the epic title in inscriptional capitals (Gladiator's Trajan), the sci-fi title in disjointed Helvetica Black (Alien).", standsFor: "EB Garamond for Apple Garamond; Cinzel for Trajan; Liberation Sans Bold for Helvetica Black.", faces: ["EBGaramond-Regular", "Cinzel-Regular", "LiberationSans-Bold"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "EBGaramond-Regular", sizePct: 4.4, holdS: 5, use: "the closing copy, one or two sentences on black" }, title: { preset: "title", font: "Cinzel-Regular", transform: "tracked-upper", sizePct: 8, shadow: 0, use: "the epic title, spaced capitals" } },
    never: ["lower-third", "caption", "callout", "citation", "label"], note: "Surveyed: Alien's Helvetica Black title (R/Greenberg), Gladiator's Trajan-class title, Apple's 1984 copy in Apple Garamond." }, "Ridley Scott"),
  T({ style: "spike-jonze", signature: "Small, lower-case and unhurried, like the 'her' wordmark; the spot's only text is the deadpan line at the end.", standsFor: "Nunito (rounded humanist) for the soft lower-case of the titles.", faces: ["Nunito-Regular"], case: "lower", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "Nunito-Regular", transform: "lower", sizePct: 4.8, use: "the last line, lower-case, on black" }, title: { preset: "title", font: "Nunito-Regular", transform: "lower", sizePct: 7, shadow: 0, use: "a title, lower-case" } },
    never: ["lower-third", "caption", "callout", "citation", "intertitle"], note: "Assumption: the 'her' title face was not documented; the manner (small, lower-case, light) is." }, "Spike Jonze"),
  T({ style: "jonathan-glazer", signature: "Small spaced capitals in a plain grotesk, white on black, once — Under the Skin's credits; the spot's line at the end.", standsFor: "Liberation Sans for the plain grotesk.", faces: ["LiberationSans-Regular"], case: "tracked-upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "card",
    roles: { card: { preset: "card-archive", font: "LiberationSans-Regular", transform: "tracked-upper", sizePct: 3.6, use: "the line at the end, spaced capitals on black" }, title: { preset: "title", font: "LiberationSans-Regular", transform: "tracked-upper", sizePct: 5, shadow: 0, use: "a title, small" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "intertitle"], note: "Surveyed: Under the Skin's credits are white lettering on black; the Guinness spots end on the brand's serif line — here a small spaced grotesk." }, "Jonathan Glazer"),
  T({ style: "hal-riney", signature: "A warm serif card for the name and the line, soft white, a slow fade.", standsFor: "EB Garamond for a warm serif.", faces: ["EBGaramond-Regular", "EBGaramond-Bold"], case: "sentence", color: "#FFF6E8", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "EBGaramond-Bold", sizePct: 5, holdS: 4, use: "the name and the line at the end" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "intertitle"], note: "Assumption: the closing card ('President Reagan: Leadership That's Working') is set in a serif; the exact face was not documented." }, "Hal Riney"),
  // ---------------------------------------------------------------- music video
  T({ style: "michel-gondry", signature: "A small rounded lower-case credit, once, lower-left; nothing else on the frame.", standsFor: "Nunito for the rounded lower-case of the Eternal Sunshine title.", faces: ["Nunito-Regular"], case: "lower", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "credit",
    roles: { credit: { preset: "citation", font: "Nunito-Regular", transform: "lower", sizePct: 3, boxEnabled: false, shadow: 4, animation: "NONE", holdS: 4, use: "artist · song, small, lower-left, first and last five seconds" } },
    never: ["lower-third", "caption", "callout", "card", "intertitle", "quote", "date", "label"], note: "Surveyed loosely: Eternal Sunshine's title is small, rounded and lower-case." }, "Michel Gondry"),
  T({ style: "hype-williams", signature: "The 1990s MTV credit block: bold Helvetica capitals, white, lower-left, three lines — artist, song, director.", standsFor: "Liberation Sans Bold for Helvetica Bold.", faces: ["LiberationSans-Bold"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "credit",
    roles: { credit: { preset: "lower-third", font: "LiberationSans-Bold", transform: "upper", sizePct: 3.2, boxEnabled: false, shadow: 6, animation: "NONE", holdS: 5, use: "ARTIST / SONG / DIRECTOR, lower-left, first and last five seconds" } },
    never: ["caption", "callout", "card", "intertitle", "quote", "date", "label", "citation"], note: "Assumption: the network's credit block, not the director's; the gloss is in the picture." }, "Hype Williams"),
  T({ style: "anton-corbijn", signature: "Photobook captions: tiny spaced capitals in a plain grotesk, white, once.", standsFor: "Liberation Sans for the plain grotesk.", faces: ["LiberationSans-Regular"], case: "tracked-upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "credit",
    roles: { credit: { preset: "citation", font: "LiberationSans-Regular", transform: "tracked-upper", sizePct: 2.6, boxEnabled: false, shadow: 0, animation: "NONE", holdS: 4, use: "artist · song, tiny spaced capitals, lower-left" }, title: { preset: "title", font: "LiberationSans-Regular", transform: "tracked-upper", sizePct: 4, shadow: 0, use: "a title, small" } },
    never: ["lower-third", "caption", "callout", "card", "intertitle", "quote", "date", "label"], note: "Assumption: Control's title face was not documented; the manner follows the photobooks." }, "Anton Corbijn"),
  T({ style: "chris-cunningham", signature: "Nothing on the frame; if a credit is needed it is small, plain and gone.", standsFor: "Liberation Sans for a plain grotesk.", faces: ["LiberationSans-Regular"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "credit", noText: true,
    roles: { credit: { preset: "citation", font: "LiberationSans-Regular", transform: "upper", sizePct: 2.8, boxEnabled: false, animation: "NONE", holdS: 3, use: "artist · song, once" } },
    never: ["lower-third", "caption", "callout", "card", "intertitle", "quote", "date", "label"], note: "The Aphex Twin mark is a custom logo; the videos carry no text." }, "Chris Cunningham"),
  // ---------------------------------------------------------------- drama
  T({ style: "wes-anderson", signature: "Futura in every film — title cards, chapter headings, signage, credits — capitals centred on a flat colour field; Archer for Isle of Dogs's credits; a script for Moonrise Kingdom.", standsFor: "Jost for Futura; Zilla Slab for Archer.", faces: ["Jost-Bold", "Jost-Medium", "ZillaSlab-Regular"], case: "upper", color: "#2B1E1A", field: "#F1D9B5", motion: "NONE", defaultRole: "intertitle",
    roles: { intertitle: { preset: "intertitle", font: "Jost-Bold", transform: "upper", sizePct: 6, color: "#2B1E1A", holdS: 3, use: "a chapter card in Futura capitals on a colour field" }, title: { preset: "title", font: "Jost-Bold", transform: "upper", sizePct: 8, color: "#2B1E1A", shadow: 0, use: "the title on the field" }, label: { preset: "map-label", font: "Jost-Medium", transform: "upper", sizePct: 3, boxEnabled: true, boxColor: "#F1D9B5", boxOpacity: 1, color: "#2B1E1A", animation: "NONE", use: "a label on an object" }, quote: { preset: "quote", font: "ZillaSlab-Regular", sizePct: 4, outlineW: 0, use: "a letter read aloud while shown" } },
    never: ["caption", "lower-third", "callout", "citation"], note: "Surveyed: Futura across the filmography; Archer in Isle of Dogs; Tilda in Moonrise Kingdom; Annie Atkins's period faces in The Grand Budapest Hotel." }, "Wes Anderson"),
  T({ style: "christopher-nolan", signature: "Heavy geometric capitals, spaced, white on black: Gotham Bold (Oppenheimer), Avenir Black (Inception), Helvetica Neue Black on the branding; Didot for Interstellar.", standsFor: "Montserrat for Gotham / Avenir / Helvetica Neue Black; Playfair Display for Didot.", faces: ["Montserrat-SemiBold", "Montserrat-Black", "PlayfairDisplay-Regular"], case: "tracked-upper", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { card: { preset: "card-archive", font: "Montserrat-SemiBold", transform: "tracked-upper", sizePct: 4, holdS: 3, use: "a timeline's clock card ('THE AIR — ONE HOUR')" }, title: { preset: "title", font: "Montserrat-Black", transform: "tracked-upper", sizePct: 8, shadow: 0, use: "the title in heavy spaced capitals" }, date: { preset: "date-card", font: "Montserrat-SemiBold", transform: "tracked-upper", sizePct: 3.4, position: "CENTER", outlineW: 0, use: "a date on black" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "quote"], note: "Surveyed: Oppenheimer Gotham Bold, Interstellar Linotype Didot, Inception Avenir Black, Helvetica Neue Black on the branding." }, "Christopher Nolan"),
  T({ style: "denis-villeneuve", signature: "Light geometric capitals with wide tracking (Arrival's lightened Gotham, Blade Runner 2049's Brandon Grotesque credits), a monumental extended wordmark (Dune) — cool white, slow.", standsFor: "Montserrat Light with spaced capitals for the light geometrics; Michroma for the extended wordmark.", faces: ["Montserrat-Light", "Michroma-Regular"], case: "tracked-upper", color: "#DCE3E8", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { title: { preset: "title", font: "Michroma-Regular", transform: "tracked-upper", sizePct: 6, shadow: 0, holdS: 5, use: "the extended, tracked title" }, card: { preset: "card-archive", font: "Montserrat-Light", transform: "tracked-upper", sizePct: 3.4, holdS: 4, use: "a chapter card, light spaced capitals" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "intertitle"], note: "Surveyed: Arrival (modified Gotham Light), Blade Runner 2049 (Brandon Grotesque credits, custom extended wordmark), Dune (custom wide geometric with extreme tracking)." }, "Denis Villeneuve"),
  T({ style: "martin-scorsese", signature: "Story-specific title identity and restrained supporting information.", standsFor: "Bundled sans and serif choices are editorial options, not verified career-wide fonts.", faces: ["Montserrat-SemiBold", "LiberationSans-Regular", "EBGaramond-Regular"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { title: { preset: "title", font: "Montserrat-SemiBold", transform: "upper", sizePct: 8, shadow: 0, holdS: 4, use: "a dedicated story-specific title" }, card: { preset: "card-archive", font: "LiberationSans-Regular", sizePct: 4, holdS: 3, use: "supporting information" }, quote: { preset: "card-archive", font: "EBGaramond-Regular", sizePct: 4, holdS: 4, use: "a verified quotation" } },
    never: [], note: "Choose a named film reference; credit Saul and Elaine Bass for the Casino title sequence. Palette and motion follow the story." }, "Martin Scorsese"),
  T({ style: "edgar-wright", signature: "1970s poster display capitals in a hot colour with an outline (Baby Driver's Gunplay), text-message bubbles and sound-effect words in the frame.", standsFor: "Anton for the Gunplay-class display; Liberation Sans Bold for the bubbles.", faces: ["Anton-Regular", "LiberationSans-Bold"], case: "upper", color: "#FFD23F", field: "#000000", motion: "POP", defaultRole: "caption",
    roles: { title: { preset: "title", font: "Anton-Regular", transform: "upper", sizePct: 9, color: "#FFD23F", outlineW: 6, shadow: 0, use: "the title, hot yellow, outlined" }, caption: { preset: "caption-pop", font: "Anton-Regular", transform: "upper", sizePct: 6, color: "#FFD23F", outlineW: 8, use: "a sound-effect word on its cut" }, label: { preset: "map-label", font: "LiberationSans-Bold", transform: "none", sizePct: 3, boxEnabled: true, boxColor: "#FFFFFF", boxOpacity: 0.92, color: "#111111", animation: "POP", use: "a text message in a bubble" } },
    never: ["lower-third", "quote", "intertitle", "citation", "date"], note: "Surveyed: Baby Driver's title in Gunplay (after The Getaway's poster); the on-screen texts follow the films' in-world graphics." }, "Edgar Wright"),
  T({ style: "terrence-malick", signature: "A small, delicate serif title on black, spaced; nothing else, ever.", standsFor: "Cormorant Garamond for the delicate serif.", faces: ["CormorantGaramond-Regular"], case: "tracked-upper", color: "#F5F0E6", field: "#000000", motion: "FADE", defaultRole: "title", noText: true,
    roles: { title: { preset: "title", font: "CormorantGaramond-Regular", transform: "tracked-upper", sizePct: 4.6, shadow: 0, holdS: 5, use: "the title, small spaced capitals on black" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "card", "intertitle", "quote", "date"], note: "Assumption: The Tree of Life's title face was not documented; the manner (small, delicate, on black, alone) is." }, "Terrence Malick"),
  // ---------------------------------------------------------------- political
  T({ style: "frank-capra", signature: "Wartime title cards in heavy gothic capitals, maps with stencilled place names, a quotation card with attribution.", standsFor: "Oswald Bold for the poster gothics; Liberation Sans for the map names.", faces: ["Oswald-Bold", "LiberationSans-Regular"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "intertitle",
    roles: { intertitle: { preset: "intertitle", font: "Oswald-Bold", transform: "upper", sizePct: 7, use: "a chapter title in heavy capitals" }, label: { preset: "map-label", font: "LiberationSans-Regular", transform: "upper", sizePct: 3, boxEnabled: false, outlineW: 5, animation: "NONE", use: "a place name on the map" }, quote: { preset: "quote", font: "LiberationSans-Regular", sizePct: 3.8, outlineW: 0, use: "the enemy's own words, with attribution" }, title: { preset: "title", font: "Oswald-Bold", transform: "upper", sizePct: 9, use: "the series title" } },
    never: ["caption", "lower-third", "callout", "citation"], note: "Assumption: the Why We Fight lettering was not documented; heavy display capitals in the 1940s poster manner." }, "Frank Capra"),
  T({ style: "sergei-eisenstein", signature: "Soviet intertitles: heavy grotesque capitals, white on black, two or three words; the constructivist poster is the reference.", standsFor: "Anton for the heavy grotesque.", faces: ["Anton-Regular"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "intertitle",
    roles: { intertitle: { preset: "intertitle", font: "Anton-Regular", transform: "upper", sizePct: 6.5, use: "an intertitle between sequences" }, title: { preset: "title", font: "Anton-Regular", transform: "upper", sizePct: 9, use: "the title" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "quote", "date"], note: "Assumption from the films: the intertitles are heavy capitals on black; no text is ever superimposed on picture." }, "Sergei Eisenstein"),
  T({ style: "tony-schwartz", signature: "One plain card of gothic capitals on black: 'Vote for President Johnson on November 3.'", standsFor: "Libre Franklin for the Franklin / News Gothic of 1964 television.", faces: ["LibreFranklin-Bold"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "card",
    roles: { card: { preset: "card-archive", font: "LibreFranklin-Bold", transform: "upper", sizePct: 4.6, holdS: 5, use: "the choice and the date, on black, at the end" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "intertitle", "quote"], note: "Surveyed: the Daisy spot ends on a plain text card on black; the face is assumed to be a 1960s gothic." }, "Tony Schwartz"),
  T({ style: "lincoln-project", signature: "Bold condensed white capitals landing on the spoken phrase, numbers big, a verdict card on black, sources in small type.", standsFor: "Oswald Bold for the Tungsten / Knockout register; Liberation Sans for the citations.", faces: ["Oswald-Bold", "LiberationSans-Regular"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "POP", defaultRole: "caption",
    roles: { caption: { preset: "caption-pop", font: "Oswald-Bold", transform: "upper", sizePct: 6.5, outlineW: 4, use: "the key phrase as it is spoken, 2–3 words" }, callout: { preset: "caption-pop", font: "Oswald-Bold", transform: "upper", sizePct: 9, position: "CENTER", outlineW: 4, use: "a number, big" }, card: { preset: "card-archive", font: "Oswald-Bold", transform: "upper", sizePct: 6, holdS: 4, use: "the verdict on black" }, citation: { preset: "citation", font: "LiberationSans-Regular", sizePct: 2.4, use: "the source under a claim" } },
    never: ["lower-third", "quote", "intertitle", "label"], note: "Surveyed loosely from the spots: condensed bold capitals, white on darkened footage; the exact face was not documented." }, "The Lincoln Project"),
  // ---------------------------------------------------------------- trailers
  T({ style: "mark-woollen", signature: "Thin sentence-case cards on black between the lines (the Social Network's light Klavika); the title in the film's own face.", standsFor: "Montserrat Light for light Klavika / Gotham Light.", faces: ["Montserrat-Light"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "Montserrat-Light", transform: "none", sizePct: 4.2, holdS: 3, use: "a line of dialogue or a phrase, on black, between shots" }, title: { preset: "title", font: "Montserrat-Light", transform: "tracked-upper", sizePct: 6.5, shadow: 0, holdS: 4, use: "the title when the song breaks" }, date: { preset: "date-card", font: "Montserrat-Light", transform: "tracked-upper", sizePct: 3.4, position: "CENTER", outlineW: 0, use: "the date on black" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "intertitle"], note: "Surveyed: The Social Network's graphics in Klavika with Futura; the trailer's cards are thin white sans on black." }, "Mark Woollen"),
  T({ style: "buddha-jones", signature: "Extended grotesk capitals for the title (Nope's and Get Out's extended Helvetica), thin condensed single words on black between the shots.", standsFor: "Archivo Expanded Bold for Helvetica Extended; Oswald Light for the thin condensed cards.", faces: ["Archivo-ExpandedBold", "Oswald-Light"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "card",
    roles: { card: { preset: "card-archive", font: "Oswald-Light", transform: "tracked-upper", sizePct: 5, holdS: 1.5, animation: "NONE", use: "a single word on black ('WATCH.')" }, title: { preset: "title", font: "Archivo-ExpandedBold", transform: "upper", sizePct: 7, shadow: 0, use: "the title, extended capitals, on the hit" }, date: { preset: "date-card", font: "Oswald-Light", transform: "tracked-upper", sizePct: 3.6, position: "CENTER", outlineW: 0, use: "the date on black" } },
    never: ["lower-third", "callout", "quote", "label", "citation", "intertitle"], note: "Surveyed: Nope's title (modified Neue Helvetica Extended Bold; Josefin Sans in the cards), Get Out's Neue Helvetica Extended Black." }, "Buddha Jones"),
  T({ style: "av-squad", signature: "Condensed grotesk premise cards (the Trade Gothic Bold Condensed / Tungsten register), the title in heavy geometric capitals slamming in on the hit.", standsFor: "Oswald Bold for Trade Gothic Bold Condensed / Tungsten; Montserrat Black for the Gotham-class title.", faces: ["Oswald-Bold", "Montserrat-Black"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "POP", defaultRole: "card",
    roles: { card: { preset: "card-archive", font: "Oswald-Bold", transform: "upper", sizePct: 6, animation: "POP", holdS: 2.2, use: "a premise card, one line, on black" }, title: { preset: "title", font: "Montserrat-Black", transform: "tracked-upper", sizePct: 9, animation: "POP", shadow: 0, use: "the title on the biggest hit" }, date: { preset: "date-card", font: "Oswald-Bold", transform: "upper", sizePct: 4, position: "CENTER", outlineW: 0, animation: "POP", use: "the date card" }, "lower-third": { preset: "lower-third", font: "Oswald-Bold", transform: "upper", sizePct: 3, boxEnabled: false, shadow: 4, use: "the studio card at the start" } },
    never: ["quote", "citation", "label", "intertitle"], note: "Assumption from the house's trailers: condensed gothic cards and a geometric title; the specific faces are per campaign." }, "AV Squad"),
  T({ style: "a24", signature: "One typeface chosen per film — a clean serif (Hereditary), a delicate one (Midsommar), a rugged bold face (The Lighthouse) — words held alone on a flat field; the type is the identity.", standsFor: "Playfair Display for the film serifs; Jost for a geometric when the film wants one.", faces: ["PlayfairDisplay-Regular", "Jost-Regular"], case: "sentence", color: "#FFFFFF", field: "#0E0E0E", motion: "NONE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "PlayfairDisplay-Regular", transform: "none", sizePct: 5.5, animation: "NONE", holdS: 2.5, use: "a single word or line on the flat field" }, title: { preset: "title", font: "PlayfairDisplay-Regular", transform: "tracked-upper", sizePct: 7, shadow: 0, animation: "NONE", holdS: 4.5, use: "the title treatment, the last image" }, date: { preset: "date-card", font: "Jost-Regular", transform: "upper", sizePct: 3.4, position: "CENTER", outlineW: 0, animation: "NONE", use: "the date in the same manner" } },
    never: ["lower-third", "caption", "callout", "citation", "label", "intertitle"], note: "Surveyed: A24's trailers pick a serif or a display face per film and keep to one typographic idea; Playfair stands in for the serifs." }, "A24"),
  T({ style: "anais-bimpel", signature: "Condensed bold capitals on the rests, the title on the final picture-sound.", standsFor: "Oswald Bold for the condensed trailer gothics.", faces: ["Oswald-Bold"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "POP", defaultRole: "card",
    roles: { card: { preset: "card-archive", font: "Oswald-Bold", transform: "upper", sizePct: 5.5, animation: "POP", holdS: 1.5, use: "two or three words on a rest" }, title: { preset: "title", font: "Oswald-Bold", transform: "tracked-upper", sizePct: 9, animation: "POP", shadow: 0, use: "the title on the last hit" } },
    never: ["lower-third", "quote", "citation", "label", "intertitle", "callout"], note: "Assumption: the rhythmic trailers use the trailer houses' condensed gothics." }, "Anaïs Bimpel"),
  // ---------------------------------------------------------------- essay / comedy
  T({ style: "tony-zhou", signature: "A plain humanist sans: a citation under every clip, the thesis and section titles on black, marks over freezes.", standsFor: "Noto Sans for the plain sans.", faces: ["NotoSans-Regular", "NotoSans-Bold"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "citation",
    roles: { citation: { preset: "citation", font: "NotoSans-Regular", use: "film · year under the clip" }, card: { preset: "card-archive", font: "NotoSans-Bold", transform: "none", sizePct: 4.6, holdS: 3, use: "the thesis or a section title on black" }, label: { preset: "map-label", font: "NotoSans-Bold", sizePct: 3, use: "a mark or a counter on a freeze" } },
    never: ["caption", "intertitle", "quote"], note: "Assumption: the essays' face was not documented; a plain sans with the citation grammar is the manner." }, "Tony Zhou"),
  T({ style: "johnny-harris", signature: "Vox's Franklin-class grotesque (Balto): bold points in an accent colour landing on the words, small-caps map labels, serif date cards, a lower-third for a source.", standsFor: "Libre Franklin for Balto / Franklin Gothic.", faces: ["LibreFranklin-Black", "LibreFranklin-Bold", "NotoSerif-Regular"], case: "sentence", color: "#FFD400", field: "#000000", motion: "SLIDE_UP", defaultRole: "caption",
    roles: { caption: { preset: "caption-pop", font: "LibreFranklin-Black", transform: "none", sizePct: 5, color: "#FFD400", outlineW: 0, boxEnabled: false, animation: "SLIDE_UP", holdS: 2.2, use: "the point in 2–4 words, accent colour" }, label: { preset: "map-label", font: "LibreFranklin-Bold", transform: "upper", sizePct: 2.8, color: "#FFFFFF", use: "a map label landing on the word" }, date: { preset: "date-card", font: "NotoSerif-Regular", sizePct: 3.6, position: "CENTER", color: "#FFFFFF", outlineW: 0, use: "a date card in a serif" }, "lower-third": { preset: "lower-third", font: "LibreFranklin-Bold", sizePct: 3.4, color: "#FFFFFF", use: "a source's name and role" }, citation: { preset: "citation", font: "LibreFranklin-Bold", color: "#FFFFFF", use: "a source under a document" } },
    never: ["intertitle", "quote"], note: "Surveyed: Vox sets in Balto (with Harriet and Roboto Mono); Harris's own channel keeps the bold grotesque and the accent colour." }, "Johnny Harris"),
  T({ style: "christopher-guest", signature: "The 2000s DV-documentary lower-third: plain white sans with a drop shadow, no bar, cut in and out, once per subject.", standsFor: "Liberation Sans for Arial / Helvetica.", faces: ["LiberationSans-Regular"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "lower-third",
    roles: { "lower-third": { preset: "lower-third", font: "LiberationSans-Regular", sizePct: 3.6, boxEnabled: false, shadow: 6, animation: "NONE", holdS: 4, use: "name · self-description, first appearance" } },
    never: ["caption", "callout", "card", "intertitle", "quote", "date", "label", "citation"], note: "Assumption: Best in Show's lower-thirds imitate television documentary of the time." }, "Christopher Guest"),
  // ---------------------------------------------------------------- youtube
  T({ style: "mrbeast", signature: "Anton for the in-video captions, Bebas Neue for the thumbnails — heavy capitals, white with a black outline, popping on the word.", standsFor: "Anton and Bebas Neue are the real faces (both free).", faces: ["Anton-Regular", "BebasNeue-Regular"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "POP", defaultRole: "caption",
    roles: { caption: { preset: "caption-pop", font: "Anton-Regular", transform: "upper", sizePct: 7, outlineW: 10, use: "the key words as they are said" }, callout: { preset: "caption-pop", font: "Anton-Regular", transform: "upper", sizePct: 6.5, position: "CENTER", color: "#FFE600", outlineW: 10, use: "a number, big, yellow" }, label: { preset: "map-label", font: "BebasNeue-Regular", transform: "upper", sizePct: 4, boxEnabled: true, boxOpacity: 0.7, use: "a timer or a stakes counter in a corner" }, title: { preset: "title", font: "BebasNeue-Regular", transform: "upper", sizePct: 9, outlineW: 6, use: "a title card" } },
    never: ["quote", "intertitle", "citation", "date"], note: "Surveyed: Anton (captions) and Bebas Neue (thumbnails); Komika Axis in older subtitles." }, "MrBeast"),
  T({ style: "casey-neistat", signature: "Marker handwriting on paper: the day's title drawn by hand, a word scrawled over a shot.", standsFor: "Permanent Marker for the marker hand.", faces: ["PermanentMarker-Regular"], case: "lower", color: "#111111", field: "#F4F1EA", motion: "NONE", defaultRole: "title",
    roles: { title: { preset: "title", font: "PermanentMarker-Regular", transform: "none", sizePct: 7, color: "#111111", shadow: 0, animation: "NONE", holdS: 2.5, use: "the day's title, marker on paper (a card shot)" }, label: { preset: "map-label", font: "PermanentMarker-Regular", transform: "none", sizePct: 3.6, color: "#FFFFFF", boxEnabled: false, shadow: 5, animation: "NONE", use: "a word over a shot" } },
    never: ["lower-third", "caption", "callout", "citation", "quote", "intertitle", "date"], note: "Surveyed: hand-drawn marker titles and physical chapter markers." }, "Casey Neistat"),
  T({ style: "mkbhd", signature: "A clean neo-grotesque (the Helvetica / SF look), white, small, lower-left section titles, specs as callouts; the only colour is the red accent.", standsFor: "Liberation Sans for Helvetica / SF Pro (Roboto appears in some graphics).", faces: ["LiberationSans-Bold", "LiberationSans-Regular"], case: "sentence", color: "#FFFFFF", field: "#0A0A0A", motion: "FADE", defaultRole: "lower-third",
    roles: { "lower-third": { preset: "lower-third", font: "LiberationSans-Bold", sizePct: 3.6, boxEnabled: false, shadow: 0, animation: "FADE", holdS: 2.5, use: "a section title, lower-left" }, callout: { preset: "callout", font: "LiberationSans-Regular", sizePct: 3, boxOpacity: 0.35, use: "a spec when it is spoken" }, card: { preset: "card-archive", font: "LiberationSans-Regular", transform: "none", sizePct: 3.4, use: "a comparison table" } },
    never: ["caption", "intertitle", "quote", "citation"], note: "Surveyed: a clean neo-grotesque in white; Roboto named for some of the tutorials." }, "MKBHD"),
  T({ style: "tom-scott", signature: "Helvetica Black on a red band for the title, lighter Helvetica for the small text; captions for names and numbers only.", standsFor: "Liberation Sans Bold / Regular for Helvetica Black / Helvetica.", faces: ["LiberationSans-Bold", "LiberationSans-Regular"], case: "sentence", color: "#FFFFFF", field: "#C8102E", motion: "NONE", defaultRole: "lower-third",
    roles: { "lower-third": { preset: "lower-third", font: "LiberationSans-Bold", sizePct: 4.2, boxEnabled: true, boxColor: "#C8102E", boxOpacity: 1, animation: "NONE", holdS: 3.5, use: "the title on the red band" }, callout: { preset: "callout", font: "LiberationSans-Regular", sizePct: 3, boxColor: "#C8102E", boxOpacity: 0.9, animation: "NONE", use: "a name or a number, first time" }, citation: { preset: "citation", font: "LiberationSans-Regular", use: "a source or a correction" } },
    never: ["caption", "intertitle", "quote", "card", "date", "label"], note: "Surveyed: Helvetica Black for the titles, lighter Helvetica for small text; the red band is his signature." }, "Tom Scott"),
  T({ style: "veritasium", signature: "A bold geometric sans for the belief card and the diagram labels, white, with light boxes; a lower-third for the expert.", standsFor: "Montserrat for the geometric sans.", faces: ["Montserrat-SemiBold", "Montserrat-Black"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "FADE", defaultRole: "label",
    roles: { card: { preset: "card-archive", font: "Montserrat-SemiBold", transform: "none", sizePct: 4.6, use: "'Everyone thinks: …' on black" }, label: { preset: "map-label", font: "Montserrat-SemiBold", sizePct: 3, use: "a diagram label drawn on the word" }, callout: { preset: "callout", font: "Montserrat-SemiBold", use: "a number or a unit when spoken" }, "lower-third": { preset: "lower-third", font: "Montserrat-SemiBold", sizePct: 3.4, use: "the expert's name and institution" } },
    never: ["intertitle", "quote"], note: "Assumption: the channel's face was not documented; a bold geometric sans is the manner." }, "Veritasium"),
  T({ style: "vsauce", signature: "DIN Next Rounded (the Pentagram identity) for words and labels; a serif for definitions.", standsFor: "Nunito for DIN Next Rounded; Noto Serif for the definitions.", faces: ["Nunito-Bold", "NotoSerif-Regular"], case: "sentence", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "card",
    roles: { card: { preset: "card-editorial", font: "NotoSerif-Regular", sizePct: 4.6, holdS: 3, use: "a definition and its etymology on black" }, label: { preset: "map-label", font: "Nunito-Bold", sizePct: 3.4, animation: "NONE", use: "a word held up" }, citation: { preset: "citation", font: "Nunito-Bold", use: "a source" } },
    never: ["lower-third", "caption", "intertitle"], note: "Surveyed: the identity's primary typeface is DIN Next Rounded (previously Alsina); the serif for definitions is an assumption." }, "Vsauce"),
  T({ style: "mark-rober", signature: "Heavy geometric capitals for numbers and test cards, semi-bold labels on the drawings, outlined white.", standsFor: "Montserrat for the geometric sans.", faces: ["Montserrat-Black", "Montserrat-SemiBold"], case: "upper", color: "#FFFFFF", field: "#000000", motion: "POP", defaultRole: "label",
    roles: { label: { preset: "map-label", font: "Montserrat-SemiBold", sizePct: 3, boxOpacity: 0.5, use: "a physics label on the whiteboard" }, callout: { preset: "caption-pop", font: "Montserrat-Black", transform: "upper", sizePct: 5, position: "CENTER", outlineW: 8, boxEnabled: false, use: "a number with its comparison" }, card: { preset: "card-archive", font: "Montserrat-Black", transform: "upper", sizePct: 6, use: "'TEST 1' on black" } },
    never: ["quote", "intertitle", "citation"], note: "Assumption: the channel's face was not documented; heavy geometric capitals are the manner." }, "Mark Rober"),
  T({ style: "emma-chamberlain", signature: "A typewriter face (the American Typewriter / Courier register), lower-case, white with a shadow, arguing with her.", standsFor: "Courier Prime for the typewriter.", faces: ["CourierPrime-Bold", "CourierPrime-Regular"], case: "lower", color: "#FFFFFF", field: "#000000", motion: "NONE", defaultRole: "caption",
    roles: { caption: { preset: "mono-note", font: "CourierPrime-Bold", transform: "lower", sizePct: 3.6, position: "BOTTOM_CENTER", boxEnabled: false, shadow: 5, animation: "NONE", holdS: 1.8, use: "a caption that comments ('she did not do that')" }, label: { preset: "map-label", font: "CourierPrime-Regular", transform: "lower", sizePct: 3.2, boxEnabled: false, shadow: 5, animation: "NONE", use: "an arrow word" } },
    never: ["lower-third", "intertitle", "quote", "citation", "date", "card"], note: "Surveyed loosely: a typewriter face for the captions; American Typewriter is the usual identification." }, "Emma Chamberlain"),
  T({ style: "peter-mckinnon", signature: "Clean geometric capitals, spaced, for section titles (arriving on the whip), a hand-drawn brush flourish for the title (the McKinnon Brush face).", standsFor: "Montserrat for the geometric sans; Permanent Marker for the brush hand.", faces: ["Montserrat-SemiBold", "PermanentMarker-Regular"], case: "tracked-upper", color: "#FFFFFF", field: "#000000", motion: "SLIDE_UP", defaultRole: "lower-third",
    roles: { "lower-third": { preset: "lower-third", font: "Montserrat-SemiBold", transform: "tracked-upper", sizePct: 3.6, boxEnabled: false, shadow: 4, animation: "SLIDE_UP", holdS: 2.5, use: "a section title on the whip" }, title: { preset: "title", font: "PermanentMarker-Regular", transform: "none", sizePct: 7, shadow: 4, use: "the title in the brush hand" }, label: { preset: "map-label", font: "Montserrat-SemiBold", transform: "upper", sizePct: 3, use: "before / after" } },
    never: ["caption", "intertitle", "quote", "citation"], note: "Surveyed: the McKinnon Brush typeface (Oban Jones) for his branding; the section titles are a clean sans." }, "Peter McKinnon"),
];

export const typeSystemFor = (styleId: string | null | undefined): TypeSystem | undefined => (styleId ? STYLE_TYPE.find((t) => t.style === styleId) : undefined);

/** A film title has its own treatment, even when a style only defines supporting text.
 * Explicit (including deliberately quiet) title designs take precedence. */
export function roleSpecFor(style: TypeSystem | undefined | null, role: TypeRole): RoleSpec | undefined {
  if (style?.roles[role]) return style.roles[role];
  if (!style || role !== "title") return undefined;
  return {
    preset: "title", font: style.faces[0],
    transform: style.case === "sentence" ? "none" : style.case,
    sizePct: 9, sizePctVertical: 6.5, position: "CENTER",
    boxEnabled: false, outlineW: 0, shadow: 0, holdS: 4,
    use: "the name of the standalone clip or film, given its own display moment; customize the title font and palette separately from supporting text",
  };
}

/** The preset id an overlay carries: "<style>:<role>" when made through a style, else the generic preset. */
export const roleOf = (preset: string | null | undefined): TypeRole | null => {
  if (!preset) return null;
  const i = preset.indexOf(":");
  const r = (i >= 0 ? preset.slice(i + 1) : ({ "lower-third": "lower-third", callout: "callout", "caption-pop": "caption", "card-archive": "card", "card-editorial": "card", title: "title", intertitle: "intertitle", quote: "quote", "date-card": "date", "map-label": "label", "mono-note": "caption", citation: "citation" } as Record<string, TypeRole>)[preset]) as TypeRole | undefined;
  return r && TYPE_ROLES.includes(r) ? r : null;
};

/** The preset a directing style reaches for first (its default role), or the generic lower-third. */
export function presetForStyle(styleId: string | null | undefined): TypePreset {
  const ts = typeSystemFor(styleId);
  const spec = ts?.roles[ts.defaultRole];
  return presetById(spec?.preset) ?? presetById("lower-third")!;
}

/**
 * Resolve a role for a frame: the style's role spec over its base preset (or
 * the generic preset for the role when the brief names no style), then the
 * caller's overrides. The overlay's `preset` records "<style>:<role>".
 */
export function applyRole(styleId: string | null | undefined, role: TypeRole, frame: { w: number; h: number }, text: string, startS: number, overrides: Parameters<typeof applyPreset>[4] = {}): OverlayFields {
  const ts = typeSystemFor(styleId);
  const spec = roleSpecFor(ts, role);
  const base = presetById(spec?.preset ?? GENERIC_ROLE_PRESET[role]) ?? TYPE_PRESETS[0];
  const merged: TypePreset = {
    ...base,
    ...(spec?.font ? { font: spec.font } : {}),
    ...(spec?.transform ? { transform: spec.transform } : {}),
    ...(spec?.sizePct != null ? { sizePct: spec.sizePct } : {}),
    ...(spec?.sizePctVertical != null ? { sizePctVertical: spec.sizePctVertical } : spec?.sizePct != null ? { sizePctVertical: +(spec.sizePct * 0.82).toFixed(1) } : {}),
    ...(spec?.position ? { position: spec.position } : {}),
    ...(spec?.color ? { color: spec.color } : ts ? { color: ts.color } : {}),
    ...(spec?.boxEnabled != null ? { boxEnabled: spec.boxEnabled } : {}),
    ...(spec?.boxColor ? { boxColor: spec.boxColor } : {}),
    ...(spec?.boxOpacity != null ? { boxOpacity: spec.boxOpacity } : {}),
    ...(spec?.outlineW != null ? { outlineW: spec.outlineW } : {}),
    ...(spec?.shadow != null ? { shadow: spec.shadow } : {}),
    ...(spec?.animation ? { animation: spec.animation } : ts ? { animation: ts.motion } : {}),
    ...(spec?.holdS != null ? { holdS: spec.holdS } : {}),
    id: ts ? `${ts.style}:${role}` : base.id,
  };
  return applyPreset(merged, frame, text, startS, overrides);
}
