-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "musicMuted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "voMuted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "voVolume" DOUBLE PRECISION NOT NULL DEFAULT 1;
