import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * First-launch bootstrap for the desktop (SQLite) build.
 *
 * The embedded SQLite database starts empty, and the desktop bundle can't run
 * the Prisma migrate CLI. So on startup we (1) create the schema from the
 * shipped DDL (`prisma/desktop-schema.sql`, generated by
 * `pnpm db:sqlite:derive` + `prisma migrate diff`) if the DB is fresh, and
 * (2) seed an admin if there are no users. No-op on the web (Postgres) build —
 * gated on SLOPSTUDIO_DB=sqlite, which electron/main.js sets.
 */
export async function ensureDesktopDb(): Promise<void> {
  if (process.env.SLOPSTUDIO_DB !== "sqlite") return;
  const { prisma } = await import("./client");

  // Fresh DB? (no `User` table yet) -> run the shipped CREATE TABLE/INDEX DDL.
  const existing = await prisma.$queryRawUnsafe<{ name: string }[]>(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='User'",
  );
  if (existing.length === 0) {
    const ddlPath =
      process.env.SLOPSTUDIO_SCHEMA_SQL ||
      path.join(process.cwd(), "prisma", "desktop-schema.sql");
    const ddl = readFileSync(ddlPath, "utf8");
    for (const stmt of ddl.split(";").map((s) => s.trim()).filter(Boolean)) {
      await prisma.$executeRawUnsafe(stmt);
    }
    console.log("[desktop] created SQLite schema");
  }

  // Lightweight forward migrations: add columns introduced after the initial DDL
  // so existing embedded DBs upgrade in place. SQLite lacks ADD COLUMN IF NOT
  // EXISTS, so we ignore the "duplicate column" error when it's already there.
  const migrations = [
    'ALTER TABLE "Segment" ADD COLUMN "effects" JSONB',
    `ALTER TABLE "WorkspaceLayout" ADD COLUMN "section" TEXT NOT NULL DEFAULT 'video'`,
    // Portable project bundles: the absolute folder a project's file + assets
    // live in (null = legacy project under ASSET_ROOT/<projectId>).
    'ALTER TABLE "Project" ADD COLUMN "bundlePath" TEXT',
    // Per-user default base folder new project bundles are created under.
    'ALTER TABLE "User" ADD COLUMN "defaultProjectFolder" TEXT',
    // Audio Studio editable multitrack session (JSON), for reopening/re-editing.
    'ALTER TABLE "Project" ADD COLUMN "audioSession" TEXT',
  ];
  for (const stmt of migrations) {
    try {
      await prisma.$executeRawUnsafe(stmt);
    } catch {
      /* column already present */
    }
  }

  // Seed a first admin if the DB has no users.
  if ((await prisma.user.count()) === 0) {
    const { hashPassword } = await import("@/lib/auth/password");
    const email = (process.env.SLOPSTUDIO_ADMIN_EMAIL || "admin@slopstudio.local").toLowerCase();
    const password = process.env.SLOPSTUDIO_ADMIN_PASSWORD || "slopstudio";
    await prisma.user.create({
      data: { email, passwordHash: await hashPassword(password), role: "ADMIN" },
    });
    console.log(`[desktop] seeded admin ${email}`);
  }
}
