import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * First-launch bootstrap for the desktop (SQLite) build.
 *
 * The embedded SQLite database starts empty, and the desktop bundle can't run
 * the Prisma migrate CLI. So on startup we (1) create the schema from the
 * shipped DDL (`prisma/desktop-schema.sql`, generated by
 * `pnpm db:sqlite:derive` + `prisma migrate diff`) if the DB is fresh, and
 * (2) seed an admin if there are no users. No-op on the web (Postgres) build —
 * gated on SLOPSTUDIO_DB=sqlite, which electron/main.js sets.
 */
export async function ensureDesktopDb(): Promise<void> {
  if (process.env.SLOPSTUDIO_DB !== "sqlite") return;
  const { prisma } = await import("./client");

  // Performance pragmas. WAL is persistent (stored in the DB file): readers no
  // longer block on writers and each timeline edit stops rewriting the journal.
  // synchronous=NORMAL is safe with WAL (durable at checkpoint, not per write).
  // (queryRaw, not executeRaw: PRAGMAs report their value as a row.)
  for (const pragma of ["PRAGMA journal_mode=WAL", "PRAGMA synchronous=NORMAL", "PRAGMA busy_timeout=5000"]) {
    try {
      await prisma.$queryRawUnsafe(pragma);
    } catch (e) {
      console.warn(`[desktop] ${pragma} failed:`, e instanceof Error ? e.message : String(e));
    }
  }

  // Fresh DB? (no `User` table yet) -> run the shipped CREATE TABLE/INDEX DDL.
  const existing = await prisma.$queryRawUnsafe<{ name: string }[]>(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='User'",
  );
  if (existing.length === 0) {
    const ddlPath =
      process.env.SLOPSTUDIO_SCHEMA_SQL ||
      path.join(process.cwd(), "prisma", "desktop-schema.sql");
    const ddl = readFileSync(ddlPath, "utf8");
    for (const stmt of ddl.split(";").map((s) => s.trim()).filter(Boolean)) {
      await prisma.$executeRawUnsafe(stmt);
    }
    console.log("[desktop] created SQLite schema");
  }

  // Lightweight forward migrations: add columns introduced after the initial DDL
  // so existing embedded DBs upgrade in place. SQLite lacks ADD COLUMN IF NOT
  // EXISTS, so check table_info first (a failed ALTER would also make Prisma
  // print a scary "prisma:error … duplicate column" line on every launch).
  const migrations: { table: string; column: string; ddl: string }[] = [
    { table: "Segment", column: "effects", ddl: "JSONB" },
    { table: "WorkspaceLayout", column: "section", ddl: "TEXT NOT NULL DEFAULT 'video'" },
    // Portable project bundles: the absolute folder a project's file + assets
    // live in (null = legacy project under ASSET_ROOT/<projectId>).
    { table: "Project", column: "bundlePath", ddl: "TEXT" },
    // Per-user default base folder new project bundles are created under.
    { table: "User", column: "defaultProjectFolder", ddl: "TEXT" },
    // Audio Studio editable multitrack session (JSON), for reopening/re-editing.
    { table: "Project", column: "audioSession", ddl: "TEXT" },
    // Custom frame size (px); null = aspectRatio/resolution preset.
    { table: "Project", column: "frameWidth", ddl: "INTEGER" },
    { table: "Project", column: "frameHeight", ddl: "INTEGER" },
    // Export format / custom LUT / libass caption style.
    { table: "Project", column: "exportCodec", ddl: "TEXT NOT NULL DEFAULT 'h264'" },
    { table: "Project", column: "lutAssetId", ddl: "TEXT" },
    { table: "Project", column: "captionStyle", ddl: "TEXT NOT NULL DEFAULT 'OUTLINE'" },
  ];
  const columnCache = new Map<string, Set<string>>();
  for (const m of migrations) {
    let cols = columnCache.get(m.table);
    if (!cols) {
      const rows = await prisma.$queryRawUnsafe<{ name: string }[]>(`PRAGMA table_info("${m.table}")`);
      cols = new Set(rows.map((r) => r.name));
      columnCache.set(m.table, cols);
    }
    if (cols.has(m.column)) continue;
    await prisma.$executeRawUnsafe(`ALTER TABLE "${m.table}" ADD COLUMN "${m.column}" ${m.ddl}`);
    cols.add(m.column);
    console.log(`[desktop] added column ${m.table}.${m.column}`);
  }

  // Seed a first admin if the DB has no users.
  if ((await prisma.user.count()) === 0) {
    const { hashPassword } = await import("@/lib/auth/password");
    const email = (process.env.SLOPSTUDIO_ADMIN_EMAIL || "admin@slopstudio.local").toLowerCase();
    const password = process.env.SLOPSTUDIO_ADMIN_PASSWORD || "slopstudio";
    await prisma.user.create({
      data: { email, passwordHash: await hashPassword(password), role: "ADMIN" },
    });
    console.log(`[desktop] seeded admin ${email}`);
  }
}
