// AUTO-GENERATED by scripts/gen-enums.mjs — DO NOT EDIT BY HAND.
//
// Target-agnostic copies of the schema enums. Import these instead of the
// enum exports from `@prisma/client`: the SQLite (desktop) client flattens
// enums to `String` and does not export them. Shape mirrors Prisma's own
// const-object + union generation, so these are drop-in for both clients.

export const Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
export type Role = (typeof Role)[keyof typeof Role];

export const AdStatus = {
  DRAFT: "DRAFT",
  RENDERING: "RENDERING",
  DONE: "DONE",
  FAILED: "FAILED",
} as const;
export type AdStatus = (typeof AdStatus)[keyof typeof AdStatus];

export const AspectRatio = {
  R16_9: "R16_9",
  R9_16: "R9_16",
  R1_1: "R1_1",
} as const;
export type AspectRatio = (typeof AspectRatio)[keyof typeof AspectRatio];

export const Resolution = {
  R480P: "R480P",
  R720P: "R720P",
  R1080P: "R1080P",
} as const;
export type Resolution = (typeof Resolution)[keyof typeof Resolution];

export const AudioFitMode = {
  PAD_VIDEO: "PAD_VIDEO",
  TRIM_VO: "TRIM_VO",
} as const;
export type AudioFitMode = (typeof AudioFitMode)[keyof typeof AudioFitMode];

export const AudioMode = {
  TTS_FROM_SCRIPT: "TTS_FROM_SCRIPT",
  TTS_VERBATIM: "TTS_VERBATIM",
  UPLOAD_AUDIO: "UPLOAD_AUDIO",
  NONE: "NONE",
} as const;
export type AudioMode = (typeof AudioMode)[keyof typeof AudioMode];

export const ShotStatus = {
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  RENDERING: "RENDERING",
  DOWNLOADING: "DOWNLOADING",
  READY: "READY",
  FAILED: "FAILED",
} as const;
export type ShotStatus = (typeof ShotStatus)[keyof typeof ShotStatus];

export const RefRole = {
  FIRST_FRAME: "FIRST_FRAME",
  LAST_FRAME: "LAST_FRAME",
  STYLE: "STYLE",
} as const;
export type RefRole = (typeof RefRole)[keyof typeof RefRole];

export const SegmentSource = {
  AI_GENERATED: "AI_GENERATED",
  UPLOAD_VIDEO: "UPLOAD_VIDEO",
  UPLOAD_IMAGE_STILL: "UPLOAD_IMAGE_STILL",
  UPLOAD_IMAGE_DRIVER: "UPLOAD_IMAGE_DRIVER",
} as const;
export type SegmentSource = (typeof SegmentSource)[keyof typeof SegmentSource];

export const ColorLook = {
  NONE: "NONE",
  WARM: "WARM",
  COOL: "COOL",
  BW: "BW",
  VINTAGE: "VINTAGE",
  PUNCH: "PUNCH",
  TEAL_ORANGE: "TEAL_ORANGE",
  NOIR: "NOIR",
  CAMPAIGN: "CAMPAIGN",
  BLEACH: "BLEACH",
} as const;
export type ColorLook = (typeof ColorLook)[keyof typeof ColorLook];

export const FillMode = {
  LETTERBOX: "LETTERBOX",
  BLUR_FILL: "BLUR_FILL",
} as const;
export type FillMode = (typeof FillMode)[keyof typeof FillMode];

export const OverlayPosition = {
  TOP_LEFT: "TOP_LEFT",
  TOP_CENTER: "TOP_CENTER",
  TOP_RIGHT: "TOP_RIGHT",
  MIDDLE_LEFT: "MIDDLE_LEFT",
  CENTER: "CENTER",
  MIDDLE_RIGHT: "MIDDLE_RIGHT",
  BOTTOM_LEFT: "BOTTOM_LEFT",
  BOTTOM_CENTER: "BOTTOM_CENTER",
  BOTTOM_RIGHT: "BOTTOM_RIGHT",
} as const;
export type OverlayPosition = (typeof OverlayPosition)[keyof typeof OverlayPosition];

export const TextAnimation = {
  NONE: "NONE",
  FADE: "FADE",
} as const;
export type TextAnimation = (typeof TextAnimation)[keyof typeof TextAnimation];

export const Transition = {
  NONE: "NONE",
  CROSSFADE: "CROSSFADE",
  DISSOLVE: "DISSOLVE",
  FADE_BLACK: "FADE_BLACK",
  WIPE: "WIPE",
  SLIDE: "SLIDE",
} as const;
export type Transition = (typeof Transition)[keyof typeof Transition];

export const ImageMotion = {
  NONE: "NONE",
  ZOOM_IN: "ZOOM_IN",
  ZOOM_OUT: "ZOOM_OUT",
  PAN_LEFT: "PAN_LEFT",
  PAN_RIGHT: "PAN_RIGHT",
  PAN_UP: "PAN_UP",
  PAN_DOWN: "PAN_DOWN",
  SUBTLE_ZOOM_IN: "SUBTLE_ZOOM_IN",
  SUBTLE_ZOOM_OUT: "SUBTLE_ZOOM_OUT",
} as const;
export type ImageMotion = (typeof ImageMotion)[keyof typeof ImageMotion];

export const SimpleStatus = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  READY: "READY",
  FAILED: "FAILED",
} as const;
export type SimpleStatus = (typeof SimpleStatus)[keyof typeof SimpleStatus];

export const AudioAssetSource = {
  SYNTHESIZED: "SYNTHESIZED",
  UPLOADED: "UPLOADED",
} as const;
export type AudioAssetSource = (typeof AudioAssetSource)[keyof typeof AudioAssetSource];

export const AssetKind = {
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOAD_VIDEO: "UPLOAD_VIDEO",
  UPLOAD_AUDIO: "UPLOAD_AUDIO",
  OVERLAY_AUDIO: "OVERLAY_AUDIO",
  WATERMARK: "WATERMARK",
  LUT: "LUT",
  SHOT_CLIP: "SHOT_CLIP",
  VO_AUDIO: "VO_AUDIO",
  FINAL_MP4: "FINAL_MP4",
} as const;
export type AssetKind = (typeof AssetKind)[keyof typeof AssetKind];

export const StoryElementKind = {
  SCENE: "SCENE",
  CHARACTER: "CHARACTER",
  OBJECT: "OBJECT",
} as const;
export type StoryElementKind = (typeof StoryElementKind)[keyof typeof StoryElementKind];

export const JobType = {
  GEN_STORYBOARD: "GEN_STORYBOARD",
  GEN_SCRIPT: "GEN_SCRIPT",
  GEN_IMAGE: "GEN_IMAGE",
  SUBMIT_SHOT: "SUBMIT_SHOT",
  RECONCILE_VIDEO: "RECONCILE_VIDEO",
  DOWNLOAD_CLIP: "DOWNLOAD_CLIP",
  IMPORT_YOUTUBE: "IMPORT_YOUTUBE",
  IMPORT_AUDIO: "IMPORT_AUDIO",
  SYNTH_VO: "SYNTH_VO",
  ASSEMBLE_FINAL: "ASSEMBLE_FINAL",
  CLEANUP: "CLEANUP",
} as const;
export type JobType = (typeof JobType)[keyof typeof JobType];

export const JobStatus = {
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  DONE: "DONE",
  FAILED: "FAILED",
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
