/** Host-neutral interview guidance, shared by discovery and the prompt. */
export const INTERVIEW_UI =
  "Ask exactly one short question at a time, multiple choice wherever practical. Fetch interview_batch once and keep its questions as a local queue; batch refers to tool retrieval, not presentation. Do not show the whole questionnaire unless the person asks for it. " +
  "Ask clip type early, then immediately offer suggested director/studio styles. The cached style question includes optionsByGenre: select the menu keyed by answers.genre locally; for a custom clip type use the closest cached genre menu, falling back to options. Offer three names with short descriptions plus House style where the host permits four choices; allow a custom director via free text. Never use a stale menu from before the clip-type answer or re-ask an already supplied style. This menu selection needs no tool call or research. " +
  "When using the interview, collect music's role (music), then its selection (musicSelection): choose for me, a named film/series soundtrack, or specified tracks/artists/files. Store supplied names, links, paths and cue preferences verbatim in musicReference; skip questions already answered. No music skips the selection and reference questions. Explicit delegation can fill musicSelection=choose without another question; an unanswered choice cannot. If musicSelection changes, clear its dependent musicReference unless the person explicitly retains it; switching music to none clears both dependent answers. A soundtrack reference does not change the directing style. Keep the optional interview short; research and audition music after collection, and carry brief.music.brief into the plan's music brief and cue choices. " +
  "Between replies, only record the answer, skip fields already answered, and present the next queued question immediately. Do not call interview_next or interview_batch after every answer. Avoid research, file reads, style lookups, plan drafting, recaps and explanations between questions. Save detailed reasoning for after collection. " +
  "Codex: use request_user_input_async when available; use request_user_input only in a mode that permits it. Claude Code: use AskUserQuestion. Otherwise ask one question in chat. Use 2–4 short choices within the host's actual option limit, preferably the supplied options, with the recommended choice first. Keep the mapping from labels to option values; never store a label in place of an enum value. Do not add Other when the host already provides free text. " +
  "Free text is appropriate for the subject, original script/shot list, scene context, or a custom preference. When agentFills is present, use simple choices from known context if easy; do not spend a turn researching or inventing elaborate options. Preserve scripts and shot lists verbatim. For multiSelect, collect an array; use comma-separated free text if the UI cannot select several choices. " +
  "Retain unsolicited answers and extra creative direction; do not ask them again. If an earlier answer changes, discard only dependent cached choices and refresh the queue when needed. Otherwise call interview_batch again only when the queue is exhausted, to collect newly applicable questions (scene context, material text, footage licence, music selection/reference) or finish the brief. Present these follow-ups one at a time as well. interview_next is a compatibility fallback when the client cannot retain a queue. " +
  "Once collection is complete, review all answers together, resolve material contradictions, and develop the plan. An explicit 'you decide' delegates choices; state those assumptions in the plan. A pending question, preselected default, timeout or silence is never an answer or approval. Interview answers do not approve the production plan.";
