#!/usr/bin/env node
/*
 * Generate src/lib/db/enums.ts from the canonical schema.prisma enums.
 *
 * Why: the SQLite (desktop) Prisma client flattens every enum to `String`, so it
 * does NOT export the enum objects/types that the Postgres client does. App code
 * therefore can't import enum values from `@prisma/client` (they vanish under
 * SQLite). This emits a hand-owned, target-agnostic copy — const-object + union,
 * byte-identical in shape to what Prisma generates for Postgres — that both
 * builds import instead.
 *
 * Run: `pnpm gen-enums`
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const schema = readFileSync(join(here, "..", "prisma", "schema.prisma"), "utf8");

const enums = [];
const re = /^enum\s+(\w+)\s*\{([^}]*)\}/gm;
let m;
while ((m = re.exec(schema))) {
  const name = m[1];
  const members = m[2]
    .split("\n")
    .map((l) => l.replace(/\/\/.*$/, "").trim())
    .filter((l) => /^\w+$/.test(l));
  enums.push({ name, members });
}

const out = [
  "// AUTO-GENERATED by scripts/gen-enums.mjs — DO NOT EDIT BY HAND.",
  "//",
  "// Target-agnostic copies of the schema enums. Import these instead of the",
  "// enum exports from `@prisma/client`: the SQLite (desktop) client flattens",
  "// enums to `String` and does not export them. Shape mirrors Prisma's own",
  "// const-object + union generation, so these are drop-in for both clients.",
  "",
];
for (const { name, members } of enums) {
  out.push(`export const ${name} = {`);
  for (const mem of members) out.push(`  ${mem}: "${mem}",`);
  out.push("} as const;");
  out.push(`export type ${name} = (typeof ${name})[keyof typeof ${name}];`);
  out.push("");
}

const dest = join(here, "..", "src", "lib", "db", "enums.ts");
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out.join("\n"));
console.log(`Wrote ${dest} (${enums.length} enums)`);
