// Generate a project-scoped Codex server entry with absolute Windows-safe paths.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./local-runtime.mjs";

const args = process.argv.slice(2);
const urlIndex = args.indexOf("--url");
const url = new URL(urlIndex >= 0 ? args[urlIndex + 1] : "http://127.0.0.1:38473");
if (!["http:", "https:"].includes(url.protocol) || url.username || url.password) throw new Error("Use an HTTP(S) URL without embedded credentials.");
const marker = "# BEGIN SlopStudio MCP (generated by codex:setup)";
const end = "# END SlopStudio MCP";
const file = join(ROOT, ".codex", "config.toml");
const old = existsSync(file) ? readFileSync(file, "utf8") : "";
let previous = old;
if (old.includes(marker)) {
  const start = old.indexOf(marker);
  const finish = old.indexOf(end, start);
  if (finish < 0) throw new Error("Incomplete generated block in .codex/config.toml; repair it before setup.");
  previous = old.slice(0, start) + old.slice(finish + end.length);
}
if (/^\s*\[mcp_servers\.slopstudio(?:\]|\.)/m.test(previous)) {
  throw new Error("An existing slopstudio MCP entry is present; update it manually instead of overwriting it.");
}
const quote = (s) => JSON.stringify(s); // TOML basic strings use the same path escapes.
const block = `${marker}
[mcp_servers.slopstudio]
command = ${quote(process.execPath)}
args = [${quote(join(ROOT, "mcp", "run.cjs"))}]
cwd = ${quote(ROOT)}
startup_timeout_sec = 30
tool_timeout_sec = 600

[mcp_servers.slopstudio.env]
SLOPSTUDIO_URL = ${quote(url.href.replace(/\/$/, ""))}
SLOPSTUDIO_AGENT_NAME = "Codex"
${end}
`;
mkdirSync(join(ROOT, ".codex"), { recursive: true });
writeFileSync(file, `${previous.trimEnd()}${previous.trim() ? "\n\n" : ""}${block}`);
console.log(`Configured ${file}\nOpen/trust this repository in Codex and restart the MCP connection. Start SlopStudio with corepack pnpm desktop:prod.`);
